### ISSUE TITLE
Purchase event is delayed

### ISSUE THREAD

**Issue by YoanRouleau** [stape-io/gtm-server-side-wordpress-plugin#8]
Hi there,

I'm noticing delays on my purchase event trigger. Within the GTM debugger, I see that all the events are fired correclty, except for the purchase one. The datalayer.push is fired, but on the next page visit right after the order-received page.

On the following exemple, I successfully ordered on my website, and went back on the homepage (because I didn't see any purchase event after placing my order):
<img width="1113" alt="Capture d’écran 2023-11-21 à 17 23 26" src="https://github.com/stape-io/gtm-server-side-wordpress-plugin/assets/46955026/d89cc4f0-38f0-45aa-aeb3-7739b274f60c">

Have you done some tweeks or changes concerning the purchase event trigger condition??

**Comment by YoanRouleau** [comment]
While I was trying to find out where that could come from, I noticed that this bad scenario only occurs when I choose to pay using by client's bank payment plugin.

**Comment by alexbub** [comment]
Hi @YoanRouleau ,

Thank you for your interest in Stape!

We have not previously received reports of similar issues from other users and it seems the problem is indeed related to how your bank payment plugin works.
Can you please provide which plugin you use for this?
We will add this to our backlog and if we get more similar complaints we will add support for it.

**Comment by YoanRouleau** [comment]
Hi Alex!

Thank your for your fast answer. :)
We've been using Up2pay E-transactions: https://fr.wordpress.org/plugins/e-transactions-wc/
I also contacted the website's dev team and asked them to update Woocommerce and E-transactions, so we can check what is not causing this bug more accurately.

**Comment by YoanRouleau** [comment]
We've updated Woocommerce to its latest version and tested the purchase event again. It didn't fix the bug, sadly. :/

**Comment by alexbub** [comment]
Hey @YoanRouleau,

Thank you so much for letting us know and sorting out the problem. I have added this solution to the backlog. We will test and most likely use it in the next update.
